# default config.yml for MysqlEconomyBridge
# config version 1.2.0

#MySQL Database details
database:
    mysql:
        #MySQL server address
        host: 127.0.0.1
        #MySQL server port (default 3306)
        port: 3306
        #Database name (NOTE! You need to create the database, then the plugin will create the tables.)
        databaseName: 'mydatabase'
        #Tables name (the plugin will auto create it)
        tableName: 'meb_accounts'
        #User name
        user: 'admin'
        #User password
        password: 'cheesecake'