# default config.yml for MysqlEconomyBridge


database:
#Maximum amount of threads that MysqlEconomyBridge can use to perform money transfers (default:4)
    maximumThreads: 4

    
    mysql:
        host: 127.0.0.1
        port: 3306
        databaseName: 'mydatabase'
        user: 'admin'
        password: 'cheesecake'
