# default config.yml for MysqlEconomyBridge
# config version 1.1.2

database:
    mysql:
        host: 127.0.0.1
        port: 3306
        databaseName: 'mydatabase'
        user: 'admin'
        password: 'cheesecake'