# default config.yml for MysqlEconomyBridge
# config version 1.5.7

#MySQL Database details
database:
    mysql:
        #MySQL server address
        host: 127.0.0.1
        #MySQL server port (default 3306)
        port: 3306
        #Database name (NOTE! You need to create the database, then the plugin will create the tables.)
        databaseName: 'mydatabase'
        #Tables name (the plugin will auto create it)
        tableName: 'meb_accounts'
        #User name
        user: 'admin'
        #User password
        password: 'cheesecake'
 
 
#Other configurable options
General:
    #Login economy sync delay in milliseconds (default 1000 milliseconds = 1 second)
    #This delay is needed in bungeecord setups, because when you move between servers the quit and login takes place almost in the same time.
    loginSyncDelay: 1000
    #Disable players balance set to 0 after player data is uploaded to the database.
    disableEconomyReset: false
    #By default the plugin only saves online players balance to the database when they leave the server. This leaves a gate open for data loss if the server will crash.
    #To limit data loss in case the server crashes enable this saving task. It runs async so there will be no lag involved.
    dataSaveTask:
        #Enable or disable the saving task.  (true or false)
        enabled: false
        #The time between saving data in minutes.  Default 3 minutes.
        interval: 3