name: MysqlEconomyBridge
main: net.craftersland.games.money.Money
version: 1.5.6
depend: [Vault]
website: www.craftersland.net
load: STARTUP
description: Sync your economy accounts over many servers using MySQL.