name: MysqlEcoBridge
main: net.craftersland.eco.bridge.Eco
api-version: 1.16
version: 3.4.2
depend: [Vault]
website: www.craftersland.net
load: STARTUP
description: Sync your economy accounts over many servers using MySQL.