name: MysqlEcoBridge
main: net.craftersland.eco.bridge.Eco
version: 3.3.2
depend: [Vault]
website: www.craftersland.net
load: STARTUP
description: Sync your economy accounts over many servers using MySQL.